apiVersion: apps/v1
kind: Deployment
metadata: 
    name: sriram1

spec: 
   replicas: 1
   selector: 
       matchLabels: 
            name: sriram
   template: 
        metadata:
            labels:  
              name: sriram
        spec: 
          containers: 
              - name: flaskapp
                image: nginx:mainline-alpine-perl
                ports: 
                   - containerPort: 5002
