apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
  namespace: nitesh
  labels:
    app: statefulset-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-demo
  serviceName: headless
  template:
    metadata:
      labels:
        app: statefulset-demo
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c","echo $(POD_NAME) > /source/data/data.txt && sleep 3000"]
        env:
        - name:  POD_NAME
          valueFrom:
            fieldRef:
              fieldPath:  metadata.name
        volumeMounts:
        - name: source-data
          mountPath: "/source/data"
        imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: source-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi