apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: conatiner-1
      image: busybox
      command: ['sh' , '-c' , 'echo the app is running && sleep 3600' ]
  initContainers:
    - name: init-container-1
      image: busybox
      command: [ 'sh' , '-c' , 'until nslookup myservice; do echo waiting for myservice; sleep 2 ; done;' ]
    - name: init-contaoner-2
      image: busybox
      command: [ 'sh' , '-c' , 'until nslookup dbservice ; do echo waiting for dbservice; sleep 2 ; done;' ]
      
