apiVersion: batch/v1
kind: Job
metadata:
  name: my-job1
spec:
  template:
    metadata:
    spec:
      containers:
      - image: busybox
        name: my-job1
        command: ['sh', '-c', 'sleep 30']
      restartPolicy: OnFailure

