---
  - hosts: db
    become: true
    gather_facts: false
    become_method: sudo
    tasks:
      - name: install httpd server
        yum:
          name: httpd
          state: present
      - name: 
        template:
          src: index.html.j2
          dest:  /usr/share/./httpd/noindex/index.html
      - name: start service httpd
        service:
          name: httpd
          state: started
