apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx2
  namespace: nitesh
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - test              
  containers:
  - image: nginx
    name: nginx2
  restartPolicy: Always