apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx2
  namespace: nitesh
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - prod               
  containers:
  - image: nginx
    name: nginx2
  restartPolicy: Always