apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: nitesh
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Always
# nodeName: gke-cluster-1-default-pool-8fe181f5-mtkm
  nodeSelector:
    env: dev



