apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nitesh
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      labels:
       app: nginx
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "name"
        operator: "Equal"
        value: "nitesh"
        effect: "NoSchedule"